# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  secrets-in-github-actions:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      MY_KEY: ${{ secrets.MY_SECRET_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.MY_SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.MY_SECRET_TOKEN}} | sed 's/./& /g' 
      # Use a GitHub Actions secret variable in a bash shell
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_SECRET_TOKEN }}

      # A GitHub Actions if statement with a secret environment variable
      - name: Step 3 - Conditional GitHub Action (false)
        shell: bash
        env: 
          WHO_TO_TRUST: ${{ secrets.MY_SECRET_TOKEN }}
        if:  env.WHO_TO_TRUST != 'TrustNobody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"
